### PR TITLE
Add Cambridge North station

### PR DESCRIPTION
**Pull request by desbo**

### CODE REVIEW

**Comment by danielthepope** [comment]
Thanks for the PR! I'm currently in a field so I can't check anything right now.
Do you know if there are any other stations

**Comment by danielthepope** [comment]
...that have been added recently? http://www.nationalrail.co.uk/static/documents/content/station_codes.csv

**Comment by desbo** [comment]
Not sure, but it'd probably be worth polling that file and keeping a cache in memory to avoid having to update a local copy. Happy to do another PR for that if you agree.

**Comment by danielthepope** [comment]
I think the original reason I had it on a local CSV file was because the National Rail file had many megabytes of whitespace at the end. If they've fixed that then yeah, polling that CSV would be a good idea. Go for it if you've got the time (and willpower to deal with my source code) :)

**Comment by danielthepope** [comment]
Hmm, that CSV file I linked to doesn't include Cambridge North (or the other 2 stations opened in 2017), so don't bother trying to poll for updates 😉 Who'd have thought National Rail would be out of date?
I've now added the [other new stations](https://github.com/danielthepope/trntxt/commit/63b96e4c43ddd9894ade88c127f73cdfbd711aa3).

**Pull request merged**
